### PR TITLE
Remove Unwanted Content

### PR DESCRIPTION
**Pull request by AaronSchneider403**
If you don't want it anymore then remove it.

### CODE REVIEW

**Comment by Azar2477** [comment]
Yes @AaronSchneider403. We don't want it anymore.

**Comment by Azar2477** [comment]
it's taking forever @AaronSchneider403.

**Comment by AaronSchneider403** [comment]
> it's taking forever @AaronSchneider403. Do we just have to wait until tomorrow?

I don't know.

**Comment by Azar2477** [comment]
I did not know there was a approve button.

**Comment by Azar2477** [comment]
I've better contact @PechayClub for the VirusTotal API Key.

**Comment by PechayClub** [comment]
I will make a new VirusTotal API Key @Azar2477.

**Pull request merged**
